GET http://127.0.0.1:8000/api/blogs
Content-Type: application/json

{

}

###

POST http://127.0.0.1:8000/login
Content-Type: application/json

{ "username":"melv","password":"melv123" }

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{ "username":"marc","password":"marc123","email":"marc@gmail.com", "first_name":"Marc","last_name":"Garcia"}


###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1Mzc0MzAyLCJpYXQiOjE3MjUzNzI1MDIsImp0aSI6ImIwODQzZGJhYTAxZjQxMjZiZDg0MTRiM2FkYTNmNWQ2IiwidXNlcl9pZCI6Mn0.Syn9-5JAU4FwMyBc-JSvxcSvrQos1tn014rdmWSXTO4 

{"username":"marc","password":"marc123"}